language: java
install: true
sudo: false
cache:
  directories:
  - "$HOME/.m2/repository"
jdk:
- openjdk8
- openjdk10
- openjdk11
script:
- mvn clean install
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - secure: RqV5Vv/xoTta+tcBlj+u/LC7rsBA055WmqZ9V3CPP+dpXT4uOKOWE8ZdjwIHepDrmKRV4L+XXIQEeUxsxUI7mgOn9VMH98pAcs5/KZcwdlUrULvyu66EHLm6vUSGr7So5bIKV6VoEATOHl476enVXfrvNCAe1VfNt5tTu55BB1M6QYWnzIl0RJgu5svOuJ/F0dMSZgn80coL3+Ha6/r02dQWqJFo89SP5YAKe52+iWPZ4/BzDOzHZ+6xA9bsLZZd63/Ebfmd6fbyWKFJPnHU+S5vfoL9XfFwH3a2FL88cqL5ImeQ3SECbb+ZlQ50+b5NzqrRumwUF8yDf2kOLAt3pYX7MEog1DLWYDaL3kPYO5qO0XsPcvMysiCtC+K6KXxe2uvjqLFbv48KgTFF4tMjlJ+lwE462jKe5PQjSzX890HSvhtb0gAkPkkqs2wg7zVWVoBC0ZNhpoOEFtMefeWNdeRl2BEuvYnklkOe7dwiLhxpEAIgH4zcFCAtbkbGkRd5KFlPO2TyJgA5qbYTFyO65LFwQOY/rpCbdEzW5cpRyaUGXr+4IeZV/o/MrvuJzohAWs2XtQd3N784Zhxo2T11hk0Xi7yRwlh7sXTMrzxcWLbBj2m4UbEL98BleNXk23WBh6AF/2cXwvr8kLI50igqizWGZ5Bq2vvQEZ6OjErx4T0=
  - secure: M9RhmHhPatjp/tQ+57sXyzFHNh3ZWHGuG0TtnU4st6cccJwnli7yuH1Jftul2+QLOTfUFs8N1x+lS+AJg7v5N7Frmk0L9YhuY/6WcKPbC/mq3248NCGDdSJhQPhnkLjjeMcIzxPKSy9w6Dxaz/B287nNwoO2yxmqxMIxfncRMMSlNfXCl5IlPaXoRJGqopBwBGMyUe0mLCb1oFSI/VCmlxNclIMVXWmZLeMPmToBhexbVxP8NOJZiFCNLLjEp4OYjE5fW0GdzQS7PYbi3undtq45BgnDmMu2tdpHPocVpqMfs7WjF2CXw2MRpJeQbtwzpg6IP2K4//a+1dzvKgBwLWbmAzG7hl8B1MUpPIyB+BczWKdHh79phCqG+j4K4UqC61Fj3OLfHb+SDP3R266Vgmi3+adPn6pqALPe7Ma1PCm9mbCCm0GylOuocFWvvhO1OJgsqZRxL+eJGply0ig+MG45LbyjXxzdkHZCb9t73gFnC5S/xX3AxK8sywW2RGbfa/N5Bffk+7plyqnvS+KPQncHUDGm3TSV+fRFrnDv7bddnuAxw8BZjDh6TeIIwP3YCIKwFw27ZQF0ouZl902Bx2z5XDtr+TyNHSNeadhPpKdoqyAwud4I2fLwUFRllQ9RvbVpLemBwg+6tEYaetgHcCSSadylXiuXQZq0QiBVEWk=
  - secure: LQ7J4PkwCVLpV24wgI5o+sY7rPXCQORdd/gMw31/jrE1kG+odZ+fcYQDOeNI/sxi6TZX0krpCwD8WEOJCZBtAwmAR7tK51GWcY2+FfKVqX4B2Goyn4SBCnJ7CFHL1+xWnPhB7avhx8DqD50QLMFgP/lDMA4X09//we8w9Gc/ilz/X7Y2wIeglcnytCTJ7NFz309aBAa51CjjFBcteMdT8l6zNDc1euwLiG2aunSVbC/QN06K1x42q2nV6y+dqOox6vcRK+z9NEDC+OMxMXrrk3oeudw1tsYGx6Fx4CqFjN2/61/7nPqT08nN2d0WYY91W0CgAkibPDyVsArm8KqIiwKiw7tE6LpSUYCP7tOHougMY0v3bushEePbEM3x7l9yRfBKsRz1pZG7+ZYEktGeLBAGNrMIyFeqfxZ1zvbudh2UkSaXFvD/pjX6Rs7yfOUGxLj1PlKPYQOFDnJmrjySPDs8j5nl43ZAvx7J51ZthoDmZMIW5cFc3KJ2HDf6L5iivykMJXaH/E8Cln33Z025YDulm9x85ek4+fuFF8ox/6Ew0PorqCiZxvbCQJHnFsUxJOwLskbXl0jOx/utwXR8IlL6SRHl/OSWYBtkUMhLBSBI4zA4iVki7LXSWfyYPH82qTaZ5dm9wpl5TzhXXXYglYXTJCU0TWtMjtt3SOTs8p8=
