language: java
install: true
sudo: false
cache:
  directories:
  - "$HOME/.m2/repository"
jdk:
- openjdk8
- openjdk10
- openjdk11
script:
- mvn clean install
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - secure: ntU/XXCeirCqIgTHQFrwFdP8BXf+YfD5eM+OdOX1eOoOyyunB3KXlkBEAnKQnIQL4ZxqJYg4GPMewe8mBmVzRTyJ85tLezsSpMUHb9TGbKti0jCQMjouJm88XnuvzF1MHWeVcgFNgOSreFwnVsu8SRL+vgxO4+6VGjxb6WYvmYIMh8ozLOHoDRWHpZjk3mGjS7XGzczPvgCPKUcWg7r+rU2qQrGfj12JVm2oViOkV8aB94rHqniQ+MYoR1LSScrC5iZ8EAnXZ8bjf1Xr0KC/AQaP8GmT3Zakf05XCuaky2CUZPecdHelLaZVmxSAVIG4Zfquu8cKKELRj5W2dgTxY82eE/iZ/jaIEdNBlimHTdL7J7x1JFEU/roK5WrLkMao64D2BUDS9nS9vZ0jrwVxtfc26wPJ80Zlw3r5QmwIZQfXBmDyVlhW4KWSOt8U2/g3uhr/ISPOs9fX00HrU+MuQAREmhrEDrpoLFk284tD50XRmUS/PU5TcjmNs8vrtKlAJ7b+TuuPEiKcUY5kIN52VQIvUgPBHbt8xc9f9wbGOMwlRQMOuE40vCSLiTpETrpFKrM5sbW3+pkYUUhM9FpOjVVA8OBXHsd4MrCwCEVq+gDeoUmIxHIhMTycTceARLB875lrkCrsBO3SF1xm/pSLWTa7L3OS/gfJ95zAPy5WLZw=
  - secure: EgzX8rh036rSXn85DkPb+67m6tz8KLNYZtl4aI0QcP82foLt/2wAUTmfQbUj1OmK20DXiJ5xRA6JnV0R3QXgDJ1Jk+djkPHVTV49adz75N7fJpRq8WXMmT5YglZbustNo/d7FTShKrqnLesHLxYlVgr0+E94bbA9ZMs3pAOgm9OimKb8cuF9u1wvMZVfCXPtOjd/iV2LEJ7ui843xMNFNDxWLsqus/qO8QxrxY/9Exx8WsSDxnjfVGgPPe9Wn8eBs1mWsjXVOdfN/KOKpq2xP8jT2yr9TXzuoxM5A09aHRa/pu8cAn59snYKN5fCF7czT026O1lNMqNa9LZzdOCrIJkhIQ5RSZM5V2eJ7BDJwZUJ8SnswHIBguBpvlsNFOKDwOAKJ+fV4/1ufaLnlc4jC8MHwVdfEO+Yq6zPkQJwEpS2EaTStRYOha3raedF8XIJVOZmYa8i759r6xak/osfTSbXNo/YLtnIFNj9YaxAfQbFBnRYdkkVGYK0QWinXcwWxVHTQi1QvvqXOm8BgK8cb55CA5gYpL+ym9IlZhm+ac13Rs9eXsYih12URJqdhvgQxZHL6TDckqNp7zuUYvT0bGqXubhvQFQxwf+hh43LPZF6PiI+quKo3JNow1f7OaKNmoHLCdzgFgjJFpgdXjAeQWjy4fvuigWVX0ca6jOMu+A=
  - secure: PbcDzumvlLBcOFnMO0AYDhBm19jFfh645uVXJoZ2mhKXAvHJh5LUgqmgqVgUsZNgtn/HJTwGR7wKzFzhQCGRf38jBF+oK+JMNFVYPa9uhAJqxDXqZEpa57Oo/ON5FJCF6akw5w6gU7MzJA04C3OZ8cqw5cWzPNWVMYT+zSRQtr1FPQYUD+AY/fwc2Amg057waDz3CIp4YUcvrrj8YPSKUI+wYgDihWDRkEruTNaOCB8q7x2CUbOMiqdfaSz10/kOT+kt88IPJN3VHeBWaTVtHtaZTkv3hmyvZ8c85FUCbNj7GM6Qnng5SvtckZtcj0NW57KE0MKi1oWQUPsUU70/ybytxoZx/vsB8tPnhYFf0sOQDXb80xzToFcDBmP+RnfpmksYlrDjpQMY+DS1+uyjz+elR+T/EyXE18hwAS8bZKsrkfGD8B7RPoo94gb9I4268HKRBspvMF6fnkEeE36lUx47Ww+OZmp7wiugywqZF66cM3aEAWtjWdWrt0/ztCd5+oXqIQXXkHzn77mWnQCOpmKFwmCBfx8wrOE0CXH4oLkwH2ubtJHP5lxrYR9Nh26rfhITB/xYFuzF5vHoO0HcVGOvHhM0an2zjyg9UrMoXnBmqxETfMrUbizNdykno9djLuGofRYah5WyZaarGm4eGnQ0Qa3otBcAuGZz7Ht83B8=
