language: java
install: true
sudo: false
cache:
  directories:
  - "$HOME/.m2/repository"
jdk:
- openjdk8
- openjdk10
- openjdk11
script:
- mvn clean install
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - secure: XZOSjZDUEXUL9ztVEXi6A5z/D2q0c7zjfjai0AdidJk53euaKGjYG7RE4Nm2Yu7eEqHAJxUkPJU83CV5BS7osTXyeAIA6tssTwaeyWSPOb0e+p2Pu5/BNUP8tDh2ufSBrv27zC/M+z8wsLv5rRbhQsNLeglcyBiUqTBPiK+4aAdiY7PTkJBnZ8BK5Paxuaz6rFDQo0Jm5b0osGv2NntZd3+U1TYCuhSahNA2FHx2SHu1f09Uwqi4k7BOmPZzZDmgb6P+rNQN21SFJnQcHhlA58NFTccrjQ2ig0knX2FU0epAa1iAqW1WifpkhV//ynQZ05hZbFeRgBeAcfuJsAfluL5MUvNuX5o5Q/HTvEhVJJTwGtijwEbv+UKBc2zWRPOnu5LYyqj0reVBda7roLS9KcCCRBPSSR7qCbSPoAcmcPS/TI+LM6wETNEbZIwXQ1kYswcgHPfy8i2jwgV+MIBLKv0fW7JSt/8IPj4An7CGMj58m9rEQIbFEXM1ryIgqGru7wX1rrG0/ish+uA6MvJoa8ta2gPn7nk3xI05/m315z/Uy91WsjSpZL3Zb7iOKdMKDjmcpxXdp+zR8Z+t/5wiAiG1L/41PRmIlJ1sr+N3j5PbZrFABNoh3IAD5YAQBJdCxxXBxRkg3uQKIHpmDns6qTpuofe3BqIF+wzqXgM6b38=
  - secure: Td1R4Ldy4vBaL2lW2/rl8DCdl5BXOS8xVgr2wLp5DMnaZIUSx+nRA1QA79y+az2A+vWewNUT0FayFk7eIOoco/eWAJpUMmc1eiRnL/YzfM673JGrasyglHcUZeC90VPAROOA8QoRQ4QJlV5q4lCdrcty5alqR0iqflj2EpVS5v5Hsm6FmIV1NVFwCN19U/rmHoo+JLoV29pJXlAQdPl+LESR99wJfZ89q59/2Z7cc4TVPH+l4xP4CcyG+Lq1q7R7KijHv9J4utqgQJfkdDvl+v8G80lKn+f1Dmi4MvSM7Spa4rtVn3GVkN8byAw/Obl27CSqfGYlPtvTpnA6rikcfMxTTSgZ1BgE1b8TlgmZuDKUMlaAfwkIzopULcJrdKpGFUOpx0aGVWLXb49JCzqLEBgBet84P+2NTJKBxG8zZlR2unJSGGtqhmrU/5QpB64BdUPoleAWa+CSD63DaQBeg/TD9UnTS1yIEzP3YbiaK+LQKXzHWRaQu8aaWbfql9bsA7gRNEkHXEG8jz9YDInkZF1OnMHXYrN1Q6TV3EsuVzJxHoS8H5i/0c/fXmHKEGTb6jtjVP2RbFaP+BMEHdj8JVMgdcyBLUJZGK/DuUumcLf1DPrLEoetRqjrAi212IScfzeWyC5S6krKxR3JLO69+0HiOHbl53+wblwM0YC2kzo=
  - secure: cI+8aOpWHL5rhx3yDjAEadLKn8ws4PX4/KdH05OlSxkUlKdhuWpT0SQZbR2/W25pnpMm62s7LWzXp+D3ELuDgwWFLDIsBpfw3iWZxeCs98Da8lql84nNSzWqeKpx2i3SFQfuUIEz3Q0oC11II4wt3RYmovuXUgjRvsHsO/V9rE9d6rYtgkav+/mq9ZvmaHyqLjLK75f4aNeOoRxv99MDg3Jp0o9XjbVj9NEIrd4OD8V5lNEJzydxIhAeBBWpCVk04+io9o3H6oeHFfpCjMNjIhzz6clnJ+C8F68MprqwMZz9HQZ3xF925c2CzRaPKP6QqDgm0zAqIr0IfIX+DCQjgHNLaR6N4wmBTgWlllj7T0uPSg9KgAex9o2GZp9ZKK2bxZh4/8QmFGduIMKODNAWSU9DDaG8jaOjT+2sCcFiaHFOrViFdQGWezTB2ObSqpWaqW+Jf9rOpoe6fRDinuqX7oUL5JWGGDEkDMbJEWxir2ANEmjOOjIy/FCh4+PHdDAgJJ8MQAHjkiIsRcpPSVbkHSGbqx+CAuM+m/qUFx/nGgWqdj/ygpVKAUysT0x2VER8rZ0n51BPKkNT3wdndQ2BYBuGw9MIeZ+DHU9MAftPWV6v5o3bZuL70p3d0eIDurqyUbOYWD04NAkGy1KapjwvRmlUkcKjS+5SSYD8+Co7y6s=
