language: java
install: true
script:
  - mvn -Dgpg.skip install
cache:
  directories:
  - "$HOME/.m2/repository"
jdk:
- openjdk8
- openjdk10
- openjdk11
after_success:
- gpg2 --keyring=$TRAVIS_BUILD_DIR/pubring.gpg --no-default-keyring --import deployment/signingkey.asc
- gpg2 --allow-secret-key-import --keyring=$TRAVIS_BUILD_DIR/secring.gpg --no-default-keyring
  --import deployment/signingkey.asc
- mvn clean deploy --settings deployment/settings.xml -Dgpg.executable=gpg2 -Dgpg.keyname=8B5A5EF880AC4E1F1A75FA0BDA10728C21A3C514
  -Dgpg.passphrase=$PASSPHRASE -Dgpg.publicKeyring=$TRAVIS_BUILD_DIR/pubring.gpg -Dgpg.secretKeyring=$TRAVIS_BUILD_DIR/secring.gpg
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - secure: LIrKmypRtB5uRDqzYOC/lX3jb3iR3fMBCtVw9eXUcNLxB7h4kSIyfcFMafN46Oy4j9Xk5bv5/Hc3sZNV64/OiK6ppR4V8Kv5gBzYZP8QImNf3tyCuKleWNJR1aEk1VhY2SJNJAfrtwJGOcBCMkJNqTg9v6FkE5MPa/4lKzLDZ4GKzq3r0KKRrtH5aeFDNSDb8gt5/hPmgRpNedwJ5zeAclr3XsoZ9ZCb0SN2Ss/ft+EOQXkhDEDq1DhJP7B5XgbZjedLqwCsPl7wfZlLNmeiqduDWN/BCeR4zm4YVI+6SbzYixuZq4zgfk2uf1ilbmmf0N00m8kYCuFH3/vScdl85NDNffIaFH5BVNgnso74mT92sEOgE86EeGeSlxqKVelRYPrubHeU7lCMdU+VAbaWBbf0hzyxf07dffQSIg0XOEJaA0Rk6lrLr6/d6wz0TV3opHDzJSLueMVWa4kENrKKdm/WHwwzNWbHI6KgowG4+A2PLkw5gkZZ9D5fOm6UnuNBIwTvhRqXOEt4bKYhYQnra8d/w72ngA74o3VwlM6qmB7yMMxkx5pL3KvBFnTFglnRg/IEfsIr9DUI23PfC1RxPv9v9XKrmy2QzqN423mI8920I02HbsmdqYLPApbIowxbAQOdKCjXprPIEnw7rEoSy9lumxEPK/zfQhjx/eZyxdQ=
  - secure: LxubguiL58EZY/ekGdlkeEHGZS45W8j4LtVWJQjJmMjecLf/xpnzEwHKlKQ66yOpzHOQeh1PpS6/7JgJvsDXn6cJCaLcC8y6k2QBpjr8Yzy35qEIppJ1Di+WkblYjuc8tts1tm4aXgOkLku1p6ULeAvqoPQ/NucBVqEOLG/cznW3Sx/7Mj2yvUX/mSSYmifs/IlpHye7BDlCue7dFe1JUBIYLq89pKGsUieTFEz1gmgTM+xuX1VdYgPzP7GDg6WDjuRNO4vR4AFlaisI4FZjEMBTe8AkjQ/s52jLM7ZvnVQ7W3WagD+iZmCLpoPzCaZ6hm2rSPpOv8Y9tWY8ICo9TqjQ14HEPeF+lBV0faj1H6NT8nLu/fPRgrSNGy4W5h3Ff0L7coiXqbj6SOEFDEHpEf3w5pX1yDKFytVN5MXqEVeij5YIn6pLYY4TsZGn0Z0W3k1cLxpycmCt7Lf2CE0C1YxDG/hgE/Jj9GGLVvCQDbv3v+/nxdFr3N04QujTaBnhWA/MypK+081uPNmADZFv9ETTVUuBnwE7u4f8X1i+5MHI8KZGb1dTjrK4WFZGui/DejG1mOWN1OTC1oCEVY16NPSf3ukwRt/9Ilq4aTpImsqNdtfPK6whMw7AbElt0JO+rpc24Yx+oU9zRSgkMJvZzVyUjIp16KRmWqFT9Mve8aY=
  - secure: mkvZ8q2n0hFGoeki+GMOx3Pw4FjGyJboveE99v3fiM9e0sipibIcbdG04OdK5s6ARK8PxoZcG4D6imAEu5b94rtSFx3gh0Me89NIWLRoatuIJHPgqkxiphIbPTVMcZXf2nk+UOgrWqlk5Y+ttH79PIwxjyATqkZoJENXRF0p9EOWpjiug80NFNxxvnqqn6PtsR1pXtdbJGhwOBRQvkNJYq0a1wW5TLrZJEIgzrcNhiyXFjwvq4afFg86+PvLXNcj4US3zFbky0y1N6mspsaBoIHE0HGQvXtkW7SZTHrg+fFY4AeaXOhxotIG/O+7MUCHoJaOss0xYLqaAEULTA0KlFMUVDD1213dVD6xjQBrcGpcX0GSb045xO+feX0LarIG7pXdJoNQyCd7UFo4xQZzjmacM+ZPc9xsXLBK7+OJZfwh4joBSCvqd91g77Apzevr4T93caX/aZfC0NeFui8RXVfrSvvA+YycTJEYolPWeQboqX1cUMV9P4LuWBPXbadH8clXK6tQIOQKS/HPj76WWScW1KkN50H8hzMg43QnZ1GMZJfw62L0TCujnTdvwuVuqlSMVMXsU3rJm/AG9LTNp9VFmv6bQWrCiRzbAlkqHaWX7c0qKZa4BgFrrKGgR1D5BqcWJDiF6FvZ5AR1j2dmEwbm2BAfiSNiU4IWDe4FWhs=
before_install:
- openssl aes-256-cbc -K $encrypted_f20a692666da_key -iv $encrypted_f20a692666da_iv
  -in deployment/signingkey.asc.enc -out deployment/signingkey.asc -d